# Laboratorio #6

* Josue Say - 228801
* Flavio Galán - 22386

## Repositorio

- [Enlace](https://github.com/JosueSay/labs-ds/tree/main/lab6)

In [1]:
# %pip install -r requirements.txt

## Constantes y liberias

In [11]:
import pandas as pd
import numpy as np
import re
import nltk

In [3]:
DATA_DIR = "data/"
DATA = "train.csv"

In [30]:
data = pd.read_csv(DATA_DIR + DATA)

data

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1
...,...,...,...,...,...
7608,10869,NaN,NaN,Two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@aria_ahrary @TheTawniest The out of control w...,1
7610,10871,NaN,NaN,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,1
7611,10872,NaN,NaN,Police investigating after an e-bike collided ...,1
7612,10873,NaN,NaN,The Latest: More Homes Razed by Northern Calif...,1

## Data Cleaning

Para la limpieza de la data se realizaron las siguientes actividades:

- Se llenaron todos los NA con una cadena vacía.
- Se quitaron todos los hashtags. (Se tuvo que evaluar si estaban al inicio/en medio o al final de la cadena).
- Se quitaron todas las menciones. (Se tuvo que evaluar si estaban al inicio/en medio o al final de la cadena).
- Se quitaron todas las URLs.
- Se quitaron todos los símbolos de puntuación. (Se hace luego de las URLs para no afectar a la detección de URLs).
- Se volvió todo a minúsculas. (Se hace hasta el final para forzar a que los RegExp de antes no sean afectados por esta transformación, por ejemplo algunos caracteres en minúscula puede que cambien por otro, o cuál es la minúscula de un emoji?).
- Finalmente se quitaron todas las `stopwords` del idioma inglés.

In [31]:
word = "[a-zA-Zñ_-]+"
url = r"[a-z]+://(\.?[a-zA-Z_-]*)+(/?[A-Za-z_\-%0-9]*)+"
emoji = r"([\u2700-\u27BF]|[\uE000-\uF8FF]|\uD83C[\uDC00-\uDFFF]|\uD83D[\uDC00-\uDFFF]|[\u2011-\u26FF]|\uD83E[\uDD10-\uDDFF]|[\\r])"
data.fillna("")
# Remove all hashtags
data['text'] = data.apply(lambda row: re.sub(f'^.*#{word} ', " ", row["text"]),axis=1)
data['text'] = data.apply(lambda row: re.sub(f'^.*#{word}$', " ", row["text"]),axis=1)
# Remove all mentions
data['text'] = data.apply(lambda row: re.sub(f'^.*@{word} ', " ", row["text"]),axis=1)
data['text'] = data.apply(lambda row: re.sub(f'^.*@{word}$', " ", row["text"]),axis=1)
# Remove all URLs
data['text'] = data.apply(lambda row: re.sub(url, " ", row["text"]),axis=1)
# Remove all punctuation
data['text'] = data.apply(lambda row: re.sub(r"[',.:()\[\]¿?¡!]", "", row["text"]),axis=1)
data['text'] = data.apply(lambda row: re.sub(r'"', "", row["text"]),axis=1)
# Remove all emojis
data['text'] = data.apply(lambda row: re.sub(emoji, "", row["text"]),axis=1)
# Lowercase everything
data['text'] = data.apply(lambda row: row["text"].lower(),axis=1)

stp = nltk.corpus.stopwords.words('english')
data['text'] = data.apply(lambda row: " ".join([w for w in row["text"].split() if w not in stp]), axis=1)

In [32]:
# 7611
data.get(7610)
data.iloc[7610]["text"]
data

,id,keyword,location,text,target
0,1,NaN,NaN,may allah fogive us,1
1,4,NaN,NaN,foest fie nea la ronge sask canada,1
2,5,NaN,NaN,esidents asked shelte place ae notified office...,1
3,6,NaN,NaN,evacuation odes califonia,1
4,7,NaN,NaN,pous school,1
...,...,...,...,...,...
7608,10869,NaN,NaN,two giant canes holding bidge collapse neaby h...,1
7609,10870,NaN,NaN,contol wild fies califonia even nothen pat sta...,1
7610,10871,NaN,NaN,m194 0104 utc5km volcano hawaii,1
7611,10872,NaN,NaN,police investigating afte e-bike collided ca l...,1
7612,10873,NaN,NaN,latest moe homes razed nothen califonia wildfi...,1